# Generated by Django 4.1.6 on 2023-02-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_created_ad_plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_ad_plus',
        ),
    ]
